// qhlist100000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "ÁÖÕðÄÏ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ê·ÇàÉ½",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶À±ÛÉñÄá",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "×¯·òÈË",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¸ßÑå³¬",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¹Ø°²»ù",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¼ÖÀÏÁù",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÀîÁ¦ÊÀ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ã©Ê®°Ë",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ë«¶ù",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÎâÁùÆæ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÐìÌì´¨",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "×¯ÔÊ³Ç",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶ÎÓþ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÆÃ¼´óÊ¦",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ôÏÈÉú",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ä¾ÍñÇå",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÆÆàÁ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÆÆÒÉ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÖÓËÄÉ©",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "´ÞïÚÍ·",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ê·ïÚÍ·",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Íõ·òÈË",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ö£ïÚÍ·",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ºúì³",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÏôÔ¶É½",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·¶Ò»·É",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·çÁ¼",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¸ßÈýÄï×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "º«±¦¾Ô",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "º«Ð¡Ó¨",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¿ÂÕò¶ñ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÂÀÕýÆ½",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÄÏÏ£ÈÊ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "È«½ð·¢",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ð¡¾Õ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ð¡À¼",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Â½¹ÚÓ¢",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÅ°¢Éú",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Öì´Ï",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÁÖ³¯Ó¢",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ð¡ÁúÅ®",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ËïÆÅÆÅ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÀîãäÜÆ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÏòÎÊÌì",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÒÇºÍ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶¨¾²Ê¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÒÇÁÕ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇØ¾î",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÒÇÇå",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÒÇÎÄ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶¨ÏÐÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶¨ÒÝÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ö£Ýà",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÒÇÖÊ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÁõÕý·ç",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Áõ·òÈË",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÁõÝ¼",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÁõÇÛ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ã×ÎªÒå",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Äª´ó",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇúÑó",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ïò´óÄê",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Çú·ÇÑÌ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÒÇÁÕ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ô¬×ÏÒÂ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÀÏÐã²Å",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "×æÇ§Çï",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Â½´óÓÐ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¸ß¸ùÃ÷",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ð¡Ê¦ÃÃ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Áº·¢",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Áîºü³å",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Â½´óÓÐ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÈÎÓ¯Ó¯",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ê©´÷×Ó",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÔÀÁéÉº",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÌÇàËª",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·ûÃôÒÇ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾Õ½£",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "À¼½£",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ê¯É©",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÓàÆÅÆÅ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µ¤ÇàÉú",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶¡¼á",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ºÚ°××Ó",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÆÖÓ¹«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ê©ÁîÍþ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Íº±ÊÎÌ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÂÖ¾Òæ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÌÑþåÈ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "´ÞÖ¾·½",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·¿Ö¾Æð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ºÂ´óÍ¨",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¼§ÇåÐé",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÀîÖ¾³£",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Áõ´¦Ðþ",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÂíîÚ",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Æ¤ÇåÐþ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÆîÖ¾³Ï",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Çð´¦»ú",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÉêÖ¾·²",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ëï²»¶þ",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ì·´¦¶Ë",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÍõÖØÑô",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Íõ´¦Ò»",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÍõÖ¾Ì¹",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÒüÖ¾Æ½",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÅÖ¾¹â",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÆ¾­µÀ³¤",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÆÀíµÀ³¤",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÆÒ©µÀ³¤",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÆÔ°µÀ³¤",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÔÖ¾¾´",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Öª¿ÍµÀ³¤",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Áõ¹úÐù",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇÇÈý»±",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·½âù",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ãå½£ÆÁ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÔÆËØÃ·",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³Ù°Ù³Ç",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "½¨³ýµÀÈË",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "½­°ÙÊ¤",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ìì°ØµÀÈË",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÌìÃÅµÀÈË",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÌìËÉµÀÈË",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÌìÒÒµÀÈË",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÌÓ¢",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÖÜ²®Í¨",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "±¾²Î",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "±¾³¾",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "±¾¹Û",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "±¾Ïà",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "±¾Òò",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¿ÝÈÙ´óÊ¦",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¸Ê±¦±¦",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÆÃ¼´óÊ¦",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ä¾ÍñÇå",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÖÓÁé",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "°××ÔÔÚ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ê·ÆÅÆÅ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ê¯ÆÆÌì",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·ë°¢Èý",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¹¶¶Á",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¿µ¹ãÁê",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ËÕÐÇºÓ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "åÐÒ£×Ó",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ñ¦Ä½»ª",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "°¢·²Ìá",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Áõ³Ð·ç",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Â½ÌìÊã",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ë®á·",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ñë×Ú",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "×¿Âê",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "°¢±Ì",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "°¢Öì",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "°ÍÌìÊ¯",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µ¶°×·ï",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶ÎÕý´¾",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·¶æè",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¸µË¼¹é",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¸ßÉýÌ©",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¹ÅóÆ³Ï",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ªºÕôÞ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Öìµ¤³¼",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ñÒÍòÀï",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "±´½õÒÇ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²µÀÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µÀÃ÷Ð¡Ê¦¸¸",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶¡Ãô¾ý",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·½±ÌÁÕ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²·çÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²ºÍÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²»ÛÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¼ÍÏþÜ½",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²åÈÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²¿ÕÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÀîÃ÷Ï¼",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÔÁéÖé",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ãð¾øÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ËÕÃÎÇå",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²ÏÐÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²ÐÄÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²ÐéÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²ÐþÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²ÕÕÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¾²ÕæÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÖÜÜÆÈô",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ºÎ²»¾»",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ºéÆß¹«",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¼ò³¤ÀÏ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "½­ÉÏÓÎ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¿Õ¿Õ¶ù",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Àî¸«Í·",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÀèÉú",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Áº³¤ÀÏ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Â³ÓÐ½Å",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Âí¾ãÎª",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÓàºéÐË",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "×óÈ«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "°«ÀÏÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³É²»ÓÇ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "´Ô²»Æú",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·â²»Æ½",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·çÇåÑï",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¸ßÀÏÕß",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Áîºü³å",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÔÀ²»Èº",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÔÀ·òÈË",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ã·½£",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÌìÉ½Í¯ÀÑ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÐéÖñ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·¶Ò£",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Î¤Ò»Ð¦",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ð¡ÕÑ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ð»Ñ·",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÑîåÐ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÒóÌìÕý",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÅÎÞ¼É",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³Î¹Û",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎºÍ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³Î¼Å",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³Î¼á",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³Î¾»",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÁé",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÃð",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÃ÷",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÉÐ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÊ¶",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎË¼",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÐÄ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÐÅ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÐÐ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÒâ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÓû",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÖª",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³ÎÖ¾",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "´ïÄ¦ÀÏ×æ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µÀ³¾ìøÊ¦",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µÀ³ÉìøÊ¦",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µÀ¹ûìøÊ¦",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µÀ¾õìøÊ¦",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µÀÆ·ìøÊ¦",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µÀÏàìøÊ¦",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µÀÏóìøÊ¦",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µÀÒ»ìøÊ¦",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "µÀÕýìøÊ¦",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶É¶ò",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶É½Ù",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¶ÉÄÑ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÛºÏ×ðÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»Û½à×ðÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»Û¿Õ×ðÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÛÃû×ðÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÛÈç×ðÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÛÉ«×ðÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÛÐÞ×ðÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÛÐé×ðÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÛÕæ×ðÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Çå·¨±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Çå¹Û±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇåÀÖ±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇåÉÆ±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇåÎª±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇåÎÅ±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇåÎÞ±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇåÏþ±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇåÔµ±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ðþ±¯´óÊ¦",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ðþ´È´óÊ¦",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ðþ¿à´óÊ¦",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÐþÄÑ´óÊ¦",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÐþÍ´´óÊ¦",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "·ëÄ¬·ç" ,
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÆÒ©Ê¦",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Â½³Ë·ç" ,
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇúÁé·ç" ,
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "»ÆÈØ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "¹ÈÐéµÀ³¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÄªÉù¹È",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÇåÐéµÀ³¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÅ´äÉ½",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÊØÔ°µÀ³¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ËÎÔ¶ÇÅ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÅËÉÏª",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ËÎÇàÊé",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Óáá·ÑÒ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÒóÀæÍ¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÓáÁ«ÖÛ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÕÅÈý·á",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÁéÐéµÀ³¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÖÆÏãµÀ³¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÁúµºÖ÷",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Ä¾µºÖ÷",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "³Â½üÄÏ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Âí³¬ÐË",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÐþÕêµÀ³¤",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               20
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
