// qlist10000.c
inherit SKILL;

mapping *quest = ({
        ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "Ø°Ê×",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ÑîÓÀ¸£",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "Çå·ç",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Ã÷ÔÂ",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Ìô·ò",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "´¬·ò",
                "quest_type":           "É±",
                "time":                 150,
                "exp_bonus":            40,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "É®¹÷",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "»¤ËÂÎäÉ®",
                "quest_type":           "É±",
                "time":                 150,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "Öª¿ÍÉ®",
                "quest_type":           "É±",
                "time":                 150,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ÑòÈâ´®",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ÍÐ²§É®",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ºÚÉ«ôÂôÄ",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ÇåÐéµÀ³¤",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               15
        ]),
        ([      "quest":                "Ô¿³×",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "·Ê·Ê",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÎÚÑ»",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            50,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ÑòÈâ´®",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            50,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ÇåÐÄÉ¢",
                "quest_type":           "Ñ°",
                "time":                 900,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Ð¡ËÉÊó",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "¹·Æ¤",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "µÀÍ¯",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "´óµ¶",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Ð¡À®Âï",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Í­ºÅ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "µÀÍ¯",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "³ÌÓ¢",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            30,
                "pot_bonus":            30,
                "score" :               7
        ]),
        ([      "quest":                "Í­îà",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÆÍÈË",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            50,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ïÚÍ·",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ÁÖÆ½Ö®",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ÍÐ²§É®",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "Çà²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ÓÎ·½ºÍÉÐ",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "µ¶¿Í",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÌË×ÓÊÖ",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÑÃÒÛ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "Ö£ïÚÍ·",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Á÷Ã¥Í·",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "Î¤´º·¼",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            25,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

