// qlist100000.c
inherit SKILL;

mapping *quest = ({
        ([      "quest":                "Àî½ÌÍ·",
                "quest_type":           "É±",
                "time":                 280,
                "exp_bonus":            100,
                "pot_bonus":            15,
                "score" :               150   //over
        ]),
        ([      "quest":                "Å·Ñô¿Ë",
                "quest_type":           "É±",
                "time":                 780,
                "exp_bonus":            170,
                "pot_bonus":            35,
                "score" :               150   //over
        ]),
        ([      "quest":                "·÷³¾",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               50   //over
        ]),
        ([      "quest":                "Ï¸Ìú¸Ë",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            100,
                "pot_bonus":            35,
                "score" :               50   //over
        ]),
        ([      "quest":                "´ÞÔ±Íâ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            150,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "º£¹«¹«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÆëÃ¼¹÷",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            180,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "´ÞÝºÝº",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÓÎÑ¶",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            25,
                "score" :               5
        ]),
        ([      "quest":                "¿Õ¿Õ¶ù",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            100,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "½äµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "É¨µØÉ®",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÀÍµÂÅµ",
                "quest_type":           "É±",
                "time":                 520,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Áº·¢",
                "quest_type":           "É±",
                "time":                 520,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ê©´÷×Ó",
                "quest_type":           "É±",
                "time":                 520,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¸ß¸ùÃ÷",
                "quest_type":           "É±",
                "time":                 520,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÔÀÁéÉº",
                "quest_type":           "É±",
                "time":                 520,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÀîÄª³î",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÓàÆÅÆÅ",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÂòÂôÌá",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "³ö³¾×Ó",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "À¼½£",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ã·½£",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÎÚÑ»",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            5,
                "score" :               5
        ]),
        ([      "quest":                "Å·Ñô¿Ë",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            220,
                "pot_bonus":            35,
                "score" :               20
        ]),
        ([      "quest":                "ÁÖÕðÄÏ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            160,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Ñò±Þ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            25,
                "score" :               5
        ]),
        ([      "quest":                "ÇåÎÅ±ÈÇð",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            120,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÀèÉú",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            29,
                "score" :               5
        ]),
        ([      "quest":                "×óÈ«",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            180,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÑÃÒÛ·þ",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "¹ÈÐéµÀ³¤",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            18,
                "score" :               5
        ]),
        ([      "quest":                "ÕªÐÇ×Ó",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ê¨ºð×Ó",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "³ö³¾×Ó",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "²É»¨×Ó",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ËÕÜõ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Òó½õ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÎÞ¸ùµÀ³¤",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅµ­ÔÂ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÐíÑ©Í¤",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Â½¸ßÐù",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÅÖÍ·ÍÓ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÊÝÍ·ÍÓ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÎâÁùÆæ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¾ÅÒíµÀÈË",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ê·µÇ´ï",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "µÒÐÞ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Íò´óÆ½",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "³Ù°Ù³Ç",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÒÇºÍ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÒÇÇå",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÒÇÖÊ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÒÇÎÄ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ìï²®¹â",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Â½ÌìÊã",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "»¨Ìú¸É",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Áõ³Ë·ç",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ë®á·",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ê¤ÚÐ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "±¦Ïó",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÉÆÓÂ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÓñÏô",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Ã÷Öé",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "È­Æ××Ü¾÷",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÕÆ·¨×ÜÆ×",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÆåÆ×",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÓñÅ®½£Æ×",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÌìÉ½Æ÷·¨",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÁúÈª½£",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Ê¥»ðÁî",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "¼Ò¶¡",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":            10,
                "score" :               15
        ]),
        ([      "quest":                "ÐþÕêµÀÈË",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            80,
                "pot_bonus":            27,
                "score" :               5
        ]),
        ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            7,
                "score" :               5
        ]),
        ([      "quest":                "¸ßÑå³¬",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "½¨³ýµÀÈË",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

