// qlist200000.c

inherit SKILL;

mapping *quest = ({
        ([      "quest":                "»ÆÃ¼´óÊ¦",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¶ÎÓþ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¶ÎÕý´¾",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "µ¶°×·ï",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¸ßÉýÌ©",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            180,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ä¾ÍñÇå",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            240,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "¹ù¾¸",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            240,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "Ãð¾øÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            240,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "ÖÜÜÆÈô",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            240,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "ÐéÖñ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "½ðÂÖ·¨Íõ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "¼ÎÄ¾»î·ð",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ñªµ¶ÀÏ×æ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "³Â½üÄÏ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
         ]),
        ([      "quest":                "ºéÆß¹«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "½ðÂÖ·¨Íõ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ð¯Ä¦ÖÇ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¶¡´ºÇï",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¶ÎÑÓÇì",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "´ïÄ¦ÀÏ×æ",
                "quest_type":           "É±",
                "time":                 1800,
                "exp_bonus":            500,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ðþ´È´óÊ¦",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÐþÄÑ´óÊ¦",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ðþ±¯´óÊ¦",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ðþ¿à´óÊ¦",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÐþÍ´´óÊ¦",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¿ÝÈÙ´óÊ¦",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "±¾³¾",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "±¾Ïà",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "±¾¹Û",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "±¾²Î",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "±¾²Î",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅÈý·á",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ËÎÔ¶ÇÅ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÓáÁ«ÖÛ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Óáá·ÑÒ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅËÉÏª",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅ´äÉ½",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÒóÀæÍ¤",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÄªÉù¹È",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "»ÆÒ©Ê¦",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "³ÂÐþ·ç",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ã·³¬·ç",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Â½³Ë·ç",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "·ëÄ¬·ç",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Å·Ñô·æ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Óñçá×Ó",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÓñÒô×Ó",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Óñíà×Ó",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÌìÃÅµÀÈË",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÔÀ²»Èº",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÔÀ·òÈË",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¸ßÀÏÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "°«ÀÏÕß",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Äª´ó",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Â³Á¬ÈÙ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¶¨¾²Ê¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¶¨ÏÐÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¶¨ÒÝÊ¦Ì«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "×óÀäìø",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Â½°Ø",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "·Ñ±ò",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¶¡Ãã",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÌÀÓ¢ðÀ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÖÓÕò",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "µË°ËÄê",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÖÓÕò",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "¸ß¿ËÐÂ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÑîåÐ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "·¶Ò£",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÒóÌìÕý",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ð»Ñ·",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Î¤Ò»Ð¦",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÌìÉ½Í¯ÀÑ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ºúì³",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÏòÎÊÌì",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÁúµºÖ÷",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ä¾µºÖ÷",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ïô·å",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ºé°²Í¨",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Óà²×º£",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "±ÙÐ°½£Æ×",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "ÌìÏãÌÃÁîÅÆ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "ÐÜµ¨¸É",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "ÓñÅ®½£Æ×",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "ÓÎÁú½£",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "²¹ÌìÊ¯",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "·üÄ§µ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "²¯¾í",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "²¨Ë¹³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            250,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Ä¾Óãé³",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            250,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "¶·Åñ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÀÏÉ½ÈË²Î",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            270,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÃÉº¹Ò©",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            270,
                "pot_bonus":            30,
                "score" :               5
        ]),

});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}


