// qlist60000.c
inherit SKILL;

mapping *quest = ({
        ([      "quest":                "Àî½ÌÍ·",
                "quest_type":           "É±",
                "time":                 280,
                "exp_bonus":            100,
                "pot_bonus":            15,
                "score" :               150   //over
        ]),
        ([      "quest":                "ÀÍµÂÅµ",
                "quest_type":           "É±",
                "time":                 580,
                "exp_bonus":            150,
                "pot_bonus":            25,
                "score" :               150   //over
        ]),
        ([      "quest":                "¸µË¼¹é",
                "quest_type":           "É±",
                "time":                 780,
                "exp_bonus":            200,
                "pot_bonus":            45,
                "score" :               150   //over
        ]),
        ([      "quest":                "·÷³¾",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               50   //over
        ]),
        ([      "quest":                "ºÚÉ«³¤ÉÀ",
                "quest_type":           "Ñ°",
                "time":                 700,
                "exp_bonus":            100,
                "pot_bonus":            25,
                "score" :               50   //over
        ]),
        ([      "quest":                "´ÞÔ±Íâ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":            150,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "º£¹«¹«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÆëÃ¼¹÷",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            180,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "´ÞÝºÝº",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÓÎÑ¶",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            25,
                "score" :               5
        ]),
        ([      "quest":                "¿Õ¿Õ¶ù",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":            100,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "½äµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "É¨µØÉ®",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "¹Ü¼Ò",
                "quest_type":           "É±",
                "time":                 320,
                "exp_bonus":            120,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÀîÄª³î",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÓàÆÅÆÅ",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÂòÂôÌá",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "³ö³¾×Ó",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Ã·½£",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÎÚÑ»",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            5,
                "score" :               5
        ]),
        ([      "quest":                "Å·Ñô¿Ë",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            220,
                "pot_bonus":            35,
                "score" :               20
        ]),
        ([      "quest":                "ÁÖÕðÄÏ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            160,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Ñò±Þ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            25,
                "score" :               5
        ]),
        ([      "quest":                "ÇåÎÅ±ÈÇð",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            120,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Öìµ¤³¼",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            29,
                "score" :               5
        ]),
        ([      "quest":                "×óÈ«",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            180,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÑÃÒÛ·þ",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÉÕºìµÄÌú´¸",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Á÷Ã¥Í·",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            5,
                "score" :               5
        ]),
        ([      "quest":                "ÑòÈâ´®",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            20,
                "pot_bonus":            9,
                "score" :               5
        ]),
        ([      "quest":                "ÓÎ¿Í",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            8,
                "score" :               5
        ]),
        ([      "quest":                "ÕªÐÇ×Ó",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "ÇúÁé·ç",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            290,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Å£Æ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":            5,
                "pot_bonus":            3,
                "score" :               5
        ]),
        ([      "quest":                "¼Ò¶¡",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":            10,
                "score" :               15
        ]),
        ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            7,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

