// qlist45000.c
inherit SKILL;

mapping *quest = ({
        ([      "quest":                "¿Ó¡¶ ¿",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            70,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "Ÿ¡ø‹",
                "quest_type":           "…±",
                "time":                 700,
                "exp_bonus":            90,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Œ¨Œ·∂˚◊Â≥§≈€",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                " •ª¡Ó",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "∏ﬂ—Â≥¨",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            20,
                "score" :               10
        ]),
        ([      "quest":                "∞Ÿœ„ª®",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":            10,
                "pot_bonus":            3,
                "score" :               5
        ]),
        ([      "quest":                "«ÂŒ≈±»«",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            15,
                "score" :               20
        ]),
        ([      "quest":                "ΩΩ‰÷∏",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":            30,
                "pot_bonus":            9,
                "score" :               5
        ]),
        ([      "quest":                "¡÷∆Ω÷Æ",
                "quest_type":           "…±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "¬Ùª®π√ƒÔ",
                "quest_type":           "…±",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            6,
                "score" :               5
        ]),
        ([      "quest":                "π∑∆§",
                "quest_type":           "—∞",
                "time":                 100,
                "exp_bonus":            10,
                "pot_bonus":            5,
                "score" :               5
        ]),
        ([      "quest":                "∑ÎÃ˙Ω≥",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "Ω¯œ„øÕ",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            4,
                "score" :               5
        ]),
        ([      "quest":                "–°π◊”",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            7,
                "score" :               5
        ]),
        ([      "quest":                "¥ﬁ‘±Õ‚",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "¥ﬁ›∫›∫",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            50,
                "pot_bonus":            15,
                "score" :               20
        ]),
        ([      "quest":                "º“∂°",
                "quest_type":           "…±",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            7,
                "score" :               5
        ]),
        ([      "quest":                "Ω‰µ∂",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "¡÷∆Ω÷Æ",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            13,
                "score" :               5
        ]),
        ([      "quest":                "ª§À¬Œ‰…Æ",
                "quest_type":           "…±",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "÷™øÕ…Æ",
                "quest_type":           "…±",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "π˛√‹πœ",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "∞¢¿≠ƒæ∫±",
                "quest_type":           "…±",
                "time":                 150,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "Ã´º´ Æ»˝ ∆",
                "quest_type":           "—∞",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "µ¿ÕØ",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            17,
                "score" :               15
        ]),
        ([      "quest":                "ª“…´µ¿≈€",
                "quest_type":           "—∞",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "≤®Àπ…Ã»À",
                "quest_type":           "…±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¬Ú¬ÙÃ·",
                "quest_type":           "…±",
                "time":                 700,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "∞◊“¬…Ÿ≈Æ",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":            20,
                "pot_bonus":            8,
                "score" :               5
        ]),
        ([      "quest":                "∞¢◊œ",
                "quest_type":           "…±",
                "time":                 900,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "√≈Œ¿",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "π∑∆§",
                "quest_type":           "—∞",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            9,
                "score" :               5
        ]),
        ([      "quest":                "¿ºΩ£",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "«‡…´µ¿≈€",
                "quest_type":           "—∞",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "–«Àﬁ≈…πƒ ÷",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            20,
                "pot_bonus":            8,
                "score" :               5
        ]),
        ([      "quest":                "Õ≠Ó‡",
                "quest_type":           "—∞",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "π»–Èµ¿≥§",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "≤®Àπ…Ã»À",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":            40,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "—ÃŒÌµØ",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "«Â–ƒ…¢",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            10,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

