// qslist80000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "·Ê·Ê",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¹Ü¼Ò",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Àî½ÌÍ·",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "»¨»¨¹«×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "É½ÔôÍ·",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÊËÎÀ", 
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÎèÉßÈË",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅÈý",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "³ÌÒ©·¢",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "´ÞÔ±Íâ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¹Ü¼Ò",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÍõÎå",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÁÖÆ½Ö®",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Á÷Ã¥Í·",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Æ½Ò»Ö¸",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¿Õ¿Õ¶ù",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÙþÀÏ°å",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "÷¡°Ý",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "º£¹«¹«",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¿µÇ×Íõ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÀÏð±ÆÅ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÆëÔª¿­",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÉñÕÕÉÏÈË",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ê·ËÉ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÎâÌìµÂ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¶ÎÎÞÎ·",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¶ÎÑÓÇì",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¶ñÅ«",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¹Ü¼Ò",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¹ó¹«×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºÎºìÒ©",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¼ÀË¾",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÀÏ¼ÀË¾",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÎÚÒÄÀÏ¼ÀË¾",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "×åÍ·ÈË",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "×å³¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ËÎÇàÊé",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÀÏ³¯·î",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "·ïÆß",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "·ïÒ»Ãù",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºöÂ×´ó»¢",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºöÂ×¶þ»¢",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "·ëÎý·¶",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "½¹ÎÄÆÚ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºöÂ×Èý»¢",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºöÂ×ËÄ»¢",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ëøÒ»À×",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÑÖ»ù",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÓñÕæ×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¶ÎÌìµÂ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÍêÑÕºéÁÒ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ñÒÔ²",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Àî¿ÉÐã",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Áú¿¥",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÃÉÃæÈË",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ç¬Â¡»ÊµÛ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅÕÙÖØ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "³ÉµÂµîµîÏÂµÜ×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¶«·½²»°Ü",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¼Ö²¼",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÈÕÔÂÉñ½Ì½ÌÍ½",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÈÎÎÒÐÐ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "É£ÈýÄï",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÉÏ¹ÙÔÆ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Í¯°ÙÐÜ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÑîÁ«Í¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "·¶ËÉ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÕÔº×",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅ³Ë·ç",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅ³ËÔÆ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Â³Á¬ÈÙ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ìï²®¹â",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "³ÂÐþ·ç" ,
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºîÍ¨º£",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Áº×ÓÎÌ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÂíÇàÐÛ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÂíÔô",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ã·³¬·ç" ,
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÃÉÃæÈË",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÅíÁ¬»¢",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ç®Çà½¡",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "É³Í¨Ìì",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÉòÇà¸Õ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÎâÇàÁÒ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Î÷ÏÄ±ø",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÀîÌú×ì",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¾ÅÒíµÀÈË",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÎÚÀÏ´ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¶ÎÑÓÇì",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "»Ê¹¬ÎÀÊ¿",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºÕÁ¬ÌúÊ÷",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÄÏº£öùÉñ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Å¬¶ùº£",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ê¯ÈËÎäÊ¿",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ò¶¶þÄï",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ò»Æ·ÌÃÎäÊ¿",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÔÆÖÐº×",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "°×¹êÊÙ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "³£½ðÅô",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "³Ì³°·ç",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "·â¹­Ó°",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¸ßÉ½Íõ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºúÇàÅ£",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÀäÇ«",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÀîÌìÔ«",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÅíÓ¨Óñ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ëµ²»µÃ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÌÆÑó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÍØ°Ï",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÎÅ²ÔËÉ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÐÁÈ»",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÑÕÔ«",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÒóÎÞ¸£",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÒóÎÞÂ»",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÒóÎÞÊÙ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÒóÒ°Íõ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅÖÐ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÖÜµß",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "×¯ï£",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "·½ÈËÖÇ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Óà²×º£",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºéÈËÐÛ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºîÈËÓ¢",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¼ªÈËÍ¨",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¼ÖÈË´ï",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÂÞÈË½Ü",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÉêÈË¿¡",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÓÚÈËºÀ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÓàÈËÑå",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºìÃ«¹í",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÀîÄª³î",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÙÁ¿Ü",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÓÎÑ¶",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÐÐÕß",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºé°²Í¨",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Â½¸ßÐù",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÀÏÕß",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÅÖÍ·ÍÓ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÊÝÍ·ÍÓ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ËÕÜõ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÎÞ¸ùµÀ³¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÐíÑ©Í¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Òó½õ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅµ­ÔÂ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÕÂÀÏÈý",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "²·³Á",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "µË°ËÄê",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "µÒÐÞ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¶¡Ãã",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "·Ñ±ò",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¸ß¿ËÐÂ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Â½°Ø",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "É³Ìì½­",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ê·µÇ´ï",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÌÀÓ¢ðÀ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Íò´óÆ½",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÀÖºñ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÖÓÕò",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "×óÀäìø",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Óñçá×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Óñíà×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÓñÒô×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÖÓÍò³ð",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÍÁ·Ë",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÍÁ·ËÍ·",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¶¡µ±",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ê¯ÖÐÓñ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ð»ÑÌ¿Í",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "°ÍÒÀ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "²É»¨×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "»¨Ìú¸É",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Àî½ÌÍ·",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Å·Ñô·æ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Å·Ñô¿Ë",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÅíÓÐ¾´",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "È«¹ÚÇå",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "³É²»ÓÇ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "´Ô²»Æú",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "·â²»Æ½",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÔÀ²»Èº",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÀÍµÂÅµ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ºé°²Í¨",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Â½¸ßÐù",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÅÖÍ·ÍÓ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÊÝÍ·ÍÓ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ËÕÜõ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÎÞ¸ùµÀ³¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÐíÑ©Í¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÐíÑ©Í¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Òó½õ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅµ­ÔÂ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "°¢×Ï",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "³ö³¾×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¶¡´ºÇï",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ê¨ºð×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÌìÀÇ×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÕªÐÇ×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "±¦Ïó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "´ï¶ø°Í",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "½ðÂÖ·¨Íõ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¸ðÂ×²¼",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¹±ÌÆ²Ö¹úÊ¦",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "¼ÎÄ¾»î·ð",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ð¯Ä¦ÖÇ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "À­ÕÂ»î·ð",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÁéÖÇÉÏÈË",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÈøÄ¾»î·ð",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "ÉÆÓÂ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ê¤ÚÐ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "Ñªµ¶ÀÏ×æ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "´ó±¯ÀÏÈË",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            16,
                "score" :               5
        ]),

});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

