// qslist2000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "∑ ∑ ",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "π‹º“",
                "quest_type":           "…±",
                "time":                 280,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¿ÓΩÃÕ∑",
                "quest_type":           "…±",
                "time":                 480,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "ª®ª®π´◊”",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "–°…Ω‘Ù",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "…Ω‘Ù",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                " ÀŒ¿", 
                "quest_type":           "…±",
                "time":                 480,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "ŒË…ﬂ»À",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "≥Ã“©∑¢",
                "quest_type":           "…±",
                "time":                 480,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¥ﬁ‘±Õ‚",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "π‹º“",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¡˜√•",
                "quest_type":           "…±",
                "time":                 280,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¡˜√•Õ∑",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "ø’ø’∂˘",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Ÿ˛¿œ∞Â",
                "quest_type":           "…±",
                "time":                 580,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "–°π◊”",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¿Æ¬Ô",
                "quest_type":           "…±",
                "time":                 580,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¿œ±∆≈",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "–°¡˜√•",
                "quest_type":           "…±",
                "time":                 280,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "∆Õ“€",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Œ‚÷Æ»Ÿ",
                "quest_type":           "…±",
                "time":                 480,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "–°‘Ù",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "°∏∆ΩÕ®Ô⁄æ÷°πÔ⁄Õ∑",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "∂Ò≈´",
                "quest_type":           "…±",
                "time":                 480,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "πÛπ´◊”",
                "quest_type":           "…±",
                "time":                 480,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "∫Œ∫Ï“©",
                "quest_type":           "…±",
                "time":                 680,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "º¿Àæ",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "…Ò≈©∞Ôµ‹◊”",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Œﬁ¡øΩ£µ‹◊”",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¿œ≥Ø∑Ó",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "∑Ô∆ﬂ",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "∂ŒÃÏµ¬",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¥ÛΩ±¯",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Ù√«ß’…",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "µ∂øÕ",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Ω£øÕ",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "√…√Ê»À",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "»’‘¬…ÒΩÃΩÃÕΩ",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¬Ì«‡–€",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¬Ì‘Ù",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "√…√Ê»À",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "«Æ«‡Ω°",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "…Ú«‡∏’",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Œ‚«‡¡“",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Œ˜œƒ±¯",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "¿ÓÃ˙◊Ï",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "ª π¨Œ¿ ø",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "–£Œæ",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "“ª∆∑Ã√Œ‰ ø",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "µÿ∆¶",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Ÿ¡ø‹",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "ƒÍ«·≈Æµ‹◊”",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Ω¯œ≤∂˘",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Õ¡∑À",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "Õ¡∑ÀÕ∑",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "–°Õ¡∑À",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "∂°µ±",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "∞Õ“¿",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "–«Àﬁ≈…Ó‡ ÷",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "≤…ª®◊”",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "–«Àﬁ≈…πƒ ÷",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "–«Àﬁ≈…∫≈ ÷",
                "quest_type":           "…±",
                "time":                 380,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                " ÿÀ¬…Æ±¯",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "–°¿Æ¬Ô",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":            12,
                "pot_bonus":            6,
                "score" :               20
        ]),

});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
