// qhlist1000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "¥Âπ√",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "π—∏æ",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ωª®",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¿œ≤ƒ",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≈©√Ò",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "È‘∑Ú",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ã˙Ω≥",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≈„¡∑ÕØ◊”",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∞◊“¬…Ÿ≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≈©º“∏æ≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "—æª∑",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "’≈¬Ë",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ô⁄Õ∑",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "πŸ±¯",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¿œ¥¨∑Ú",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∫ÏƒÔ",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "“©∆ÃªÔº∆",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¡÷’ƒœ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                " ∑«‡…Ω",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Œ‰Ω´",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¥ﬁ›∫›∫",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≥Ã”Òª∑",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¬Ùª®π√ƒÔ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "◊Ø∑Ú»À",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∏ﬂ—Â≥¨",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "πÀ—◊Œ‰",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "πÿ∞≤ª˘",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≈Æπ‹º“",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∫˙’∆πÒ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "øÕµÍªÔº∆",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Õ¿‘◊≥°ªÔº∆",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "“©∆ÃªÔº∆",
                "quest_type":           "ÀÕÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "º÷¿œ¡˘",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¿Ó¡¶ ¿",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ã˙Ω≥",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "œ∑◊”",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "—æª∑",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "◊Ø‘ ≥«",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≈Æπ‹º“",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "À·–„≤≈",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≤Ë≤© ø",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                " ø±¯",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ã®“ƒ…Ã∑∑",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≤……£≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≤…ÀÒ»À",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¥Â∏æ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∑ƒ…¥≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ã®“ƒ∏æ≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∏Ë≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∞⁄“ƒ≈Æ◊”",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ƒœπ˙π√ƒÔ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "π¨≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "π‹º“",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ã®“ƒπ√ƒÔ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "—¯ª®≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ªÙœ»…˙",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ω≠∫˛“’»À",
                "quest_type":           "ÀÕ",
                "time":                 300,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ø≥÷Ò»À",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                " ¢∆§¬ﬁøÕ…Ã",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∞⁄“ƒ–°∫¢",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¡‘»À",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ã®“ƒ¡‘»À",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¬Ì∑Ú",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ƒæÕÒ«Â",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ƒ¡—Ú≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ƒ¡—Ú»À",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≈©∑Ú",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ã®“ƒ≈©∏æ",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≈©∑Ú",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∞⁄“ƒ¿œ€≈",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∆§ªı…Ã",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∆∆‡¡",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∆∆“…",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "…Ÿ≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                " ØΩ≥",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ã®“ƒ…Ã∑∑",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Àÿ“¬Œ¿ ø",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ª∆“¬Œ¿ ø",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ωı“¬Œ¿ ø",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Œ⁄“ƒ…Ã∑∑",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "–°µ¿π√",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "—¶¿œ∞Â",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "—¯≤œ≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "”ŒøÕ",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "”Ê∑Ú",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "’≈≥ØÃ∆",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "’≈øµ",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "÷”Àƒ…©",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "÷”–°∂˛",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∞◊∂˛",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≥¬∆ﬂ",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¥ﬁÔ⁄Õ∑",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∏Í ≤π˛",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¡÷’ƒœ",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                " ∑Ô⁄Õ∑",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Õı∑Ú»À",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "÷£Ô⁄Õ∑",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ã´∫˛∫¿Ω‹",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                " ÈÕØ",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ÀÔ∆≈∆≈",
                "quest_type":           "ÀÕ",
                "time":                 400,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∫Ïª®ª·÷⁄",
                "quest_type":           "ÀÕ",
                "time":                 500,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¬Ã”™ª·÷⁄",
                "quest_type":           "ÀÕ",
                "time":                 500,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∫ÏƒÔ",
                "quest_type":           "ÀÕ",
                "time":                 500,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¿Ó„‰‹∆",
                "quest_type":           "ÀÕ",
                "time":                 500,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "—∆∏æ",
                "quest_type":           "ÀÕ",
                "time":                 500,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¡ı›º",
                "quest_type":           "ÀÕ",
                "time":                 500,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¡ı«€",
                "quest_type":           "ÀÕ",
                "time":                 500,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "«˙∑«—Ã",
                "quest_type":           "ÀÕ",
                "time":                 500,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¿œ–„≤≈",
                "quest_type":           "ÀÕ",
                "time":                 500,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "–° ¶√√",
                "quest_type":           "ÀÕ",
                "time":                 200,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "–°∫Ô",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¿Ó…©",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "√…√Ê≈Æ¿…",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "««»˝ª±",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "…®µÿ…Æ",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ª§¡÷…Æ±¯",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "÷¥∑®…Æ±¯",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                " ÿÀ¬…Æ±¯",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "…’∑π…Æ",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "–°…≥√÷",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "„ÂΩ£∆¡",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "‘∆Àÿ√∑",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "–°∫¢",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "À’÷›≈Æ∫¢",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "À’÷›…Ÿ≈Æ",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "”Œ∑Ω∫Õ…–",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≥Ã”¢",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ª§À˛…Æ",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¿œƒÍ…Æ»À",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "…®µÿ…Æ",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¥‰ª®",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "÷”¡È",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "–°¥‰",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∞¢¿≠ƒæ∫±",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∞¢∑≤Ã·",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¬Ú¬ÙÃ·",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "≤®Àπ…Ã»À",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "—Î◊⁄",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "◊ø¬Í",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "µ¿√˜–° ¶∏∏",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Œƒ∑Ω–° ¶Ã´",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ŒƒÍÕ–° ¶Ã´",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Œƒ«Â–° ¶Ã´",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Œƒ“Ù–° ¶Ã´",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ω≠…œ”Œ",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "øÏªÓ»˝",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "¿Ó∏´Õ∑",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ƒ™≤ª ’",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ù√ÕÚº“",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "’‘π∑∂˘",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "–°’—",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Õ–≤ß…Æ",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "–È√˜",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "–ÈÕ®",
                "quest_type":           "ÀÕ",
                "time":                 350,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "µ¿ÕØ",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∑•ƒæµ¿ ø",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "√˜‘¬",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "«Â∑Á",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                " ÿ‘∞µ¿≥§",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "÷∆œ„µ¿≥§",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "÷Ïæ≈’Ê",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "÷Ï≥§¡‰",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Œ¿Ëµ",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Œ‰«‡”ß",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "’≤¥∫",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "À’œ∞",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∏ﬂ‘Ú≥…",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ΩØÃŒ",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∞¢±Ã",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∞¢÷Ï",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∞¸≤ªÕ¨",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∑Á≤®∂Ò",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "∫⁄“¬∞Ô÷⁄",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "ª““¬∞Ô÷⁄",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "–°ÕØ",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
        ([      "quest":                "Ù√«ß’…",
                "quest_type":           "ÀÕ",
                "time":                 450,
                "exp_bonus":            4,
                "pot_bonus":            2,
                "score" :               20
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
